# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 80
  connection-timeout: 5000ms
  servlet:
    context-path: /

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  #    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

app:
  filePath: D:\web\
  excel_model: 2
  allow: http://127.0.0.1
  key: admin
  secret: 0mDtVmlTeC35vOVK
